### ISSUE TITLE
Works for all brands and type?

### ISSUE THREAD

**Issue by WimVriend** [dburckh/AndroidPing#2]
Hello Dustin,

I am looking for an Android Ping implementation that will work, regardless of brand and type of phone. Do you have any idea if this is the case for AndroidPing?

FYI: I am creating an App that will send data over wifi to a PC. I want the users to be able to ping their PC, so they can test the communication. Other ping implementation(s) (like the system ping) seem to work only on specific phones...

**Comment by dburckh** [comment]
It should work for any Lollipop or greater device.  I can't say it will
work for every device, but we using it in a production system with around
500K devices.  You might want to ping a know public host to test the
functionality.  The other alternative is to shell out and execute ping from
the command line.

Here's a stackoverflow with more info.

https://stackoverflow.com/questions/3905358/how-to-ping-external-ip-from-java-android


You can bind the process to a specific interface or I believe ping has an
option to specify the interface.

Dustin

**Comment by WimVriend** [comment]
Hello Dustin,

Thanks for your answer. If you have that many devices using it and have not received a wave of feedback, saying that it does not work, then I suppose it works :)

Maybe this is a stupid question (I am not that experienced with Android programming): what is the best way to incorporate it into my own App?

**Comment by dburckh** [comment]
Yeah, our product intelligence team that would definitely let me know if
things were broken.  For most projects I create an artifact, but since this
is so small I would just copy the two classes in this dir:

https://github.com/dburckh/AndroidPing/tree/master/lib/src/main/java/com/spectrum/android/ping


Dustin

**Comment by WimVriend** [comment]
Hi Dustin,

OK, I figured that would be the answer. Yesterday I fiddled with it a bit more and I managed to get it working nicely. Now I will have my testers try it too.

Since communication is the topic: do you also have a solution for Android to PC (Windows) communication over USB? I would love to add USB communication as an alternative to Wifi.

**Comment by dburckh** [comment]
I've actually done quite a bit of Android USB.  That said, your best bet
would be to stick with the MTP built into Android.  It will allow you to
transfer most files.  A custom USB solution is going to get complicated
fast.  You'll need a Windows USB driver and an Android driver.  That's not
trivial.  I think a more straightforward approach would be to write a
Windows App that instructs the user to put the Android device into MTP mode
and then detects it.  If necessary you could create a companion Android app.

Dustin

**Comment by WimVriend** [comment]
Hello Dustin,

Well, thanks for the tip. I have done some reading and a bit of experimenting. To be honest, I do not think that the USB-way is the way for me. The problem is, that I want to communicate real-time data to the PC. MTP and PTP are not exactly meant for that. Also, the user would have to dig deep into the Android settings (developer options and such) to set the USB mode. 

As you mention creating a custom USB solution would involve creating drivers and such. Even though I like a challenge, I do not think that this challenge is worth the effort. Wifi communication already works and I only seek for an alternative, for users who have difficulties connecting to their PC...

I do also investigate Bluetooth serial communication. The problem with that is, that it can be difficult to configure Bluetooth for a PC (I'm using an USB adapter for Bluetooth). All in all, the wifi solution seems the most practical...

**Comment by dburckh** [comment]
I think you are confusing ADB/USB debugging with MTP.  MTP can enabled via
a notification you get when you attach the phone to the PC.  On older
devices it's enabled by default.  That said, MTP is not a stream protocol.
You could poll files, but that's not great.

If you are using networking you might want to looking to mDNS or some sort
of discovery protocol.  That would make a much better user experience.

Dustin

**Comment by WimVriend** [comment]
You are right: MTP was enabled even on this old Samsung. But I wanted to check PTP and RNDIS and to switch between those, I had to go into the developer options...

Do you mean that I could save the user the trouble of entering an IP-address, by using mDNS?
Can I create such a service in the application that's running on the PC?

**Comment by dburckh** [comment]
MTP is an extension to PTP, so it should behave the same.

Yeah mDNS (aka Bonjour) is a service discovery protocol.  You would need to
have one side act as the server and the other as a client.  I know Android
has some support via the MediaRouter, but you would have to do some
research.  I assume Windows has some services too.

Dustin

**Comment by WimVriend** [comment]
Hello Dustin,

I'm not so sure if mDNS is going to make things more user-friendly. From what I read on the internet, it may also be blocked by routers and firewalls, so that problem remains :(

**Comment by dburckh** [comment]
I assumed you are trying to use it for devices on the same local network.
Yes, mDNS is a LAN protocol, so it generally won't work on WANs.  Since
most modern devices use it for discovery (e.g. Chromecast), it's usually
not blocked.

Dustin
