### ISSUE TITLE
Timems returned -1

### ISSUE THREAD

**Issue by hungdev** [dburckh/AndroidPing#3]
Hi @dburckh 
What does it mean timeMs = -1?

**Comment by dburckh** [comment]
Means the ping timed out.  See Ping.TIMED_OUT_MS.

It is reasonable to expect some level of failure.

Dustin

**Comment by hungdev** [comment]
@dburckh thanks for your reply.
Is it mean the library doesn't work? Because it always returns timeMs = -1. I don't know why. I pinged google.com
![image](https://user-images.githubusercontent.com/12009276/146125628-459e03ee-8d5d-4d79-9a40-3a320f942ec6.png)

**Comment by dburckh** [comment]
I just ran it on my S20 and Pixel 3a and it's working.  Can you ping from
the command line, e.g. "adb shell ping google.com"?

Dustin

**Comment by hungdev** [comment]
I can ping it from terminal:
![image](https://user-images.githubusercontent.com/12009276/146302643-16fef8c5-aed7-4f8a-934a-50bb5dbe10f3.png)

**Comment by dburckh** [comment]
That's from your Windows box, not the phone.  Are you trying to run the
sample on an emulator?  The emulator may not work.  It uses some Linux
Kernel magic  that may not be present in the emulator.

Dustin

**Comment by hungdev** [comment]
yes. I'm trying to run it on the emulator. Let me try it on real device. Thank you.

**Comment by hungdev** [comment]
@dburckh  thank you. It worked on a real device. 
but I hope you publish it to the library for easy installation.
